// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orennkhlzmlhbhmtkxiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yZW5ua2hsem1saGJobXRreGl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzODY5MjgsImV4cCI6MjA3NDk2MjkyOH0.N-3mDmI_kkWQxctxolhTs8RZ6JfDIXTgrTMpFNh0tXU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});